authapp/urls.py
from django.urls import path

from authapp import views
from authapp.apps import AuthappConfig

app_name = AuthappConfig.name

urlpatterns = [
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", views.CustomLogoutView.as_view(), name="logout"),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("profile_edit/<int:pk>/", views.ProfileEditView.as_view(), name="profile_edit"),
]

braniaclms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='mainapp/')),
    path('mainapp/', include('mainapp.urls', namespace="mainapp"))

]

library/library/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from mainapp.views import AuthorModelViewSet


router = DefaultRouter()
router.register('authors', AuthorModelViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
]

mainapp/urls.py
from django.urls import path
from mainapp import views
from mainapp.apps import MainappConfig


app_name = MainappConfig.name


urlpatterns = [

    path('', views.IndexView.as_view(), name="index"),
    path('contacts/', views.ContactView.as_view(), name="contacts"),
    path('courses/', views.CoursesListView.as_view(), name="courses"),
    path('docsite/', views.DocSiteView.as_view(), name="docsite"),
    path('login/', views.LoginView.as_view(), name="login"),
    path('news/', views.NewsView.as_view(), name="news"),
    path("news/<int:page>/", views.NewsWithPaginatorView.as_view(), name="news_paginator"),





    # path('', views.HelloWorldView.as_view()),
    # path('blog/', views.blog),

]

library/mainapp/models.py
from django.db import models
from uuid import uuid4


class Author(models.Model):
    id = models.UUIDField(default=uuid4, primary_key=True)
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    birthday_year = models.PositiveIntegerField()

mainapp/models.py
from django.db import models

# Create your models here.

mainapp/models/course_feedback.py
__all__ = ['RatingChoices', 'CourseFeedback']

from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import gettext_lazy as _

# https://docs.djangoproject.com/en/4.1/ref/models/fields/#choices


class RatingChoices(models.IntegerChoices):
    ONE = (1, "⭐")
    TWO = (2, "⭐⭐")
    THREE = (3, "⭐⭐⭐")
    FOUR = (4, "⭐⭐⭐⭐")
    FIVE = (5, "⭐⭐⭐⭐⭐")


class CourseFeedback(models.Model):
    # RATING = ((5, "⭐⭐⭐⭐⭐"), (4, "⭐⭐⭐⭐"), (3, "⭐⭐⭐"), (2, "⭐⭐"), (1, "⭐"))
    course = models.ForeignKey(
        'mainapp.Courses', on_delete=models.CASCADE, verbose_name=_("Course")
    )
    user = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, verbose_name=_("User")
    )
    feedback = models.TextField(
        default=_("No feedback"), verbose_name=_("Feedback")
    )
    rating = models.SmallIntegerField(
        choices=RatingChoices.choices, default=RatingChoices.FIVE, verbose_name=_("Rating")
    )
    created = models.DateTimeField(auto_now_add=True, verbose_name="Created")
    deleted = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.course} ({self.user})"

mainapp/models/course_teachers.py
__all__ = ['CourseTeachers']

from django.db import models
from django.utils.translation import gettext_lazy as _


class CourseTeachers(models.Model):
    course = models.ManyToManyField('mainapp.Courses')
    name_first = models.CharField(max_length=128, verbose_name="Name")
    name_second = models.CharField(max_length=128, verbose_name="Surname")
    day_birth = models.DateField(verbose_name="Birth date")
    deleted = models.BooleanField(default=False)

    def __str__(self) -> str:
        return "{0:0>3} {1} {2}".format(
            self.pk, self.name_second, self.name_first
        )

    def delete(self, *args):
        self.deleted = True
        self.save()

    class Meta:  # https://django.fun/ru/docs/django/4.1/ref/models/options/ смотри подробнее
        verbose_name = _("Teacher")
        verbose_name_plural = _("Teachers")
        

mainapp/models/courses.py
__all__ = ['Courses']

from django.db import models

from mainapp.models.managers import CoursesManager


class Courses(models.Model):
    objects = CoursesManager()

    name = models.CharField(max_length=256, verbose_name="Name")
    description = models.TextField(verbose_name="Description", blank=True, null=True)
    description_as_markdown = models.BooleanField(verbose_name="As markdown", default=False)
    cost = models.DecimalField(max_digits=8, decimal_places=2, verbose_name="Cost", default=0)
    cover = models.CharField(max_length=25, default="no_image.svg", verbose_name="Cover")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Created")
    updated = models.DateTimeField(auto_now=True, verbose_name="Edited")
    deleted = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"{self.pk} {self.name}"

    def delete(self, *args):
        self.deleted = True
        self.save()

mainapp/models/lesson.py
__all__ = ['Lesson']

from django.db import models
from django.utils.translation import gettext_lazy as _


class Lesson(models.Model):
    course = models.ForeignKey('mainapp.Courses', on_delete=models.CASCADE)
    num = models.PositiveIntegerField(verbose_name="Lesson number")
    title = models.CharField(max_length=256, verbose_name="Name")
    description = models.TextField(verbose_name="Description", blank=True, null=True)
    description_as_markdown = models.BooleanField(verbose_name="As markdown", default=False)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Created", editable=False)
    updated = models.DateTimeField(auto_now=True, verbose_name="Edited", editable=False)
    deleted = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"{self.course.name} | {self.num} | {self.title}"

    def delete(self, *args):
        self.deleted = True
        self.save()

    class Meta:
        ordering = ("course", "num")
        verbose_name = _("Lesson")
        verbose_name_plural = _("Lessons")

mainapp/models/news.py
__all__ = ['News']

from django.db import models
from django.utils.translation import gettext_lazy as _


# Create your models here.
class News(models.Model):
    title = models.CharField(max_length=256, verbose_name="Title")
    preambule = models.CharField(max_length=1024, verbose_name="Preambule")
    body = models.TextField(blank=True, null=True, verbose_name="Body")
    body_as_markdown = models.BooleanField(default=False, verbose_name="As markdown")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Created", editable=False)
    updated = models.DateTimeField(auto_now=True, verbose_name="Edited", editable=False)
    deleted = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"{self.pk} {self.title}"

    def delete(self, *args):
        self.deleted = True
        self.save()


class Meta:
    verbose_name = _("News") # Название
    verbose_name_plural = _("News") # Название во множественном числе
    ordering = ("-created",) # Сортировка

mainapp/forms/feedback_form.py
from django import forms

from mainapp import models as mainapp_models
from mainapp.models import RatingChoices


class CourseFeedbackForm(forms.ModelForm):

    def __init__(self, *args, course=None, user=None, **kwargs):
        ret = super().__init__(*args, **kwargs)
        if course and user:
            self.fields["course"].initial = course.pk
            self.fields["user"].initial = user.pk
        return ret

    class Meta:
        model = mainapp_models.CourseFeedback
        fields = ("course", "user", "feedback", "rating")
        widgets = {
            "course": forms.HiddenInput(),
            "user": forms.HiddenInput(),
            "rating": forms.RadioSelect(choices=RatingChoices.choices),
        }

library/mainapp/views.py
from rest_framework.viewsets import ModelViewSet
from .models import Author
from .serializers import AuthorModelSerializer


class AuthorModelViewSet(ModelViewSet):
    queryset = Author.objects.all()
    serializer_class = AuthorModelSerializer

mainapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import TemplateView


# Create your views here.

class ContactView(TemplateView):
    template_name = 'mainapp/contacts.html'


class CoursesListView(TemplateView):
    template_name = 'mainapp/courses_list.html'


class DocSiteView(TemplateView):
    template_name = 'mainapp/doc_site.html'


class IndexView(TemplateView):
    template_name = 'mainapp/index.html'


class LoginView(TemplateView):
    template_name = 'mainapp/login.html'


class NewsView(TemplateView):
    template_name = 'mainapp/news.html'

    def get_context_data(self, **kwargs):
        # Get all previous data
        context = super().get_context_data(**kwargs)
        # Create your own data
        context["news_title"] = "Громкий новостной заголовок"
        context["news_preview"] = "Предварительное описание, которое заинтересует каждого"
        context["range"] = range(5)
        return context


class NewsWithPaginatorView(NewsView):
    def get_context_data(self, page, **kwargs):
        context = super().get_context_data(page=page, **kwargs)
        context["page_num"] = page
        return context
























# class HelloWorldView(View):
#
#     def get(self, request, *args, **kwargs):
#         return HttpResponse('hello, world!')


# def hello_world(request):
#    return HttpResponse("hello")


# def blog(request):
#     return HttpResponse("i'm blog")

mainapp/templates/mainapp/news/news.html
{% extends 'base.html' %}

{% block title %}
Новости
{% endblock title %}

    {% block content %}

<!--{% if page_num %}-->
<div class="card my-2">
  <div class="card-body">
    <p class="card-text">Текущая страница: {{ page_num }}</p>
  </div>
</div>
{% endif %}
<div class="row">

  <div class="col-lg-8">

    {% for item in news_qs %}
      {% include 'mainapp/news/includes/news_item.html' with news=item %}
    {% endfor %}



  </div>

  <div class="col-lg-4">
    <div class="card my-2 sticky-top">
      <div class="card-header">
        Фильтры
      </div>
      <div class="card-body">
        <form action="">
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon1">Дата от...</span>
            </div>
            <input type="date" class="form-control" name="dateFrom">
          </div>
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon1">Дата до...</span>
            </div>
            <input type="date" class="form-control" name="dateTo">
          </div>
          <button type="submit"
            class="btn btn-primary btn-block">Фильтровать</button>
        </form>
      </div>
    </div>
  </div>

</div>

{% include 'mainapp/includes/pagination.html' %}

{% endblock content %}

mainapp/templates/mainapp/news/news_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="row justify-content-center pt-3">
  <div class="col-md-8 col-lg-6">
    <h2>Пометить новость удалённой?</h2>
    <p>
      Поставить отметку удаления для новости:<br>
      "{{ object.title }}" от {{ object.created }}
    </p>
    <p>
    <div class="row">
      <div class="col-6">
        <form action="{% url 'mainapp:news_delete' pk=object.pk %}"
          method="post">
          {% csrf_token %}
          <button class="btn btn-danger btn-block"
            type="submit">Подтвердить</button>
        </form>
      </div>
      <div class="col-6">
        <a class="btn btn-primary btn-block" href="{% url 'mainapp:news' %}"
          role="button">Отмена</a>
      </div>
    </div>
    </p>
  </div>
</div>
{% endblock content %}}

mainapp/templates/mainapp/news/news_detail.html
{% extends 'base.html' %}

{% block title %}
{{ object.title|default:"Новости" }}
{% endblock title %}

{% block content %}
<div class="row justify-content-center pt-3">
    <div class="col-md-12 col-lg-8">
        <div class="card shadow">
            <div class="card-body">
                <h5 class="card-title">{{ object.title }}</h5>
                <p class="card-text">
                    {{ object.body }}
                </p>
                <a href="{% url 'mainapp:news' %}"
                    class="btn btn-primary">Назад</a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

mainapp/templates/mainapp/news/news_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row justify-content-center pt-3">
  <div class="col-md-12 col-lg-8">
    <form method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit"
        class="btn btn-primary btn-block">Опубликовать</button>
    </form>
  </div>
</div>
{% endblock content %}

mainapp/templates/mainapp/news/news_list.html
{% extends 'base.html' %}

{% block title %}
Новости
{% endblock title %}

    {% block content %}

<!--{% if page_num %}-->
<div class="card my-2">
  <div class="card-body">
    <p class="card-text">Текущая страница: {{ page_num }}</p>
  </div>
</div>
{% endif %}
<div class="row">

  <div class="col-lg-8">

    {% for item in object_list %}
      {% include 'mainapp/news/includes/news_item.html' with news=item %}
    {% endfor %}



  </div>

  <div class="col-lg-4">
    <div class="card my-2 sticky-top">
      <div class="card-header">
        Фильтры
      </div>
      <div class="card-body">
        <form action="">
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon1">Дата от...</span>
            </div>
            <input type="date" class="form-control" name="dateFrom">
          </div>
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon1">Дата до...</span>
            </div>
            <input type="date" class="form-control" name="dateTo">
          </div>
          <button type="submit"
            class="btn btn-primary btn-block">Фильтровать</button>
        </form>
      </div>
    </div>

      {% if perms.mainapp.add_news %}
        <a class="btn btn-primary btn-block" role="button"
          href="{% url 'mainapp:news_create' %}">Добавить новость</a>
      {% endif %}

  </div>

</div>

<div class="row justify-content-center align-items-center mt-3 mb-n3">
  <nav aria-label="Page navigation example">
    <ul class="pagination">
      <li class="page-item"><a class="page-link" href="#">Previous</a></li>
      <li class="page-item"><a class="page-link" href="#">1</a></li>
      <li class="page-item"><a class="page-link" href="#">2</a></li>
      {# <li class="page-item"><a class="page-link" href="#">3</a></li> #}
      <li class="page-item"><a class="page-link" href="#">Next</a></li>
    </ul>
  </nav>
</div>

{% endblock content %}