authapp/urls.py
from django.urls import path

from authapp import views
from authapp.apps import AuthappConfig

app_name = AuthappConfig.name

urlpatterns = [
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", views.CustomLogoutView.as_view(), name="logout"),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("profile_edit/<int:pk>/", views.ProfileEditView.as_view(), name="profile_edit"),
]

braniaclms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='mainapp/')),
    path('mainapp/', include('mainapp.urls', namespace="mainapp"))

]

library/library/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from mainapp.views import AuthorModelViewSet


router = DefaultRouter()
router.register('authors', AuthorModelViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
]

mainapp/urls.py
from django.urls import path
from mainapp import views
from mainapp.apps import MainappConfig


app_name = MainappConfig.name


urlpatterns = [

    path('', views.IndexView.as_view(), name="index"),
    path('contacts/', views.ContactView.as_view(), name="contacts"),
    path('courses/', views.CoursesListView.as_view(), name="courses"),
    path('docsite/', views.DocSiteView.as_view(), name="docsite"),
    path('login/', views.LoginView.as_view(), name="login"),
    path('news/', views.NewsView.as_view(), name="news"),
    path("news/<int:page>/", views.NewsWithPaginatorView.as_view(), name="news_paginator"),





    # path('', views.HelloWorldView.as_view()),
    # path('blog/', views.blog),

]

library/mainapp/models.py
from django.db import models
from uuid import uuid4


class Author(models.Model):
    id = models.UUIDField(default=uuid4, primary_key=True)
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    birthday_year = models.PositiveIntegerField()

mainapp/models.py
from django.db import models

# Create your models here.

mainapp/models/course_feedback.py
__all__ = ['RatingChoices', 'CourseFeedback']

from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import gettext_lazy as _

# https://docs.djangoproject.com/en/4.1/ref/models/fields/#choices


class RatingChoices(models.IntegerChoices):
    ONE = (1, "⭐")
    TWO = (2, "⭐⭐")
    THREE = (3, "⭐⭐⭐")
    FOUR = (4, "⭐⭐⭐⭐")
    FIVE = (5, "⭐⭐⭐⭐⭐")


class CourseFeedback(models.Model):
    # RATING = ((5, "⭐⭐⭐⭐⭐"), (4, "⭐⭐⭐⭐"), (3, "⭐⭐⭐"), (2, "⭐⭐"), (1, "⭐"))
    course = models.ForeignKey(
        'mainapp.Courses', on_delete=models.CASCADE, verbose_name=_("Course")
    )
    user = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, verbose_name=_("User")
    )
    feedback = models.TextField(
        default=_("No feedback"), verbose_name=_("Feedback")
    )
    rating = models.SmallIntegerField(
        choices=RatingChoices.choices, default=RatingChoices.FIVE, verbose_name=_("Rating")
    )
    created = models.DateTimeField(auto_now_add=True, verbose_name="Created")
    deleted = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.course} ({self.user})"

mainapp/models/course_teachers.py
__all__ = ['CourseTeachers']

from django.db import models
from django.utils.translation import gettext_lazy as _


class CourseTeachers(models.Model):
    course = models.ManyToManyField('mainapp.Courses')
    name_first = models.CharField(max_length=128, verbose_name="Name")
    name_second = models.CharField(max_length=128, verbose_name="Surname")
    day_birth = models.DateField(verbose_name="Birth date")
    deleted = models.BooleanField(default=False)

    def __str__(self) -> str:
        return "{0:0>3} {1} {2}".format(
            self.pk, self.name_second, self.name_first
        )

    def delete(self, *args):
        self.deleted = True
        self.save()

    class Meta:  # https://django.fun/ru/docs/django/4.1/ref/models/options/ смотри подробнее
        verbose_name = _("Teacher")
        verbose_name_plural = _("Teachers")
        

mainapp/models/courses.py
__all__ = ['Courses']

from django.db import models

from mainapp.models.managers import CoursesManager


class Courses(models.Model):
    objects = CoursesManager()

    name = models.CharField(max_length=256, verbose_name="Name")
    description = models.TextField(verbose_name="Description", blank=True, null=True)
    description_as_markdown = models.BooleanField(verbose_name="As markdown", default=False)
    cost = models.DecimalField(max_digits=8, decimal_places=2, verbose_name="Cost", default=0)
    cover = models.CharField(max_length=25, default="no_image.svg", verbose_name="Cover")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Created")
    updated = models.DateTimeField(auto_now=True, verbose_name="Edited")
    deleted = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"{self.pk} {self.name}"

    def delete(self, *args):
        self.deleted = True
        self.save()

mainapp/models/lesson.py
__all__ = ['Lesson']

from django.db import models
from django.utils.translation import gettext_lazy as _


class Lesson(models.Model):
    course = models.ForeignKey('mainapp.Courses', on_delete=models.CASCADE)
    num = models.PositiveIntegerField(verbose_name="Lesson number")
    title = models.CharField(max_length=256, verbose_name="Name")
    description = models.TextField(verbose_name="Description", blank=True, null=True)
    description_as_markdown = models.BooleanField(verbose_name="As markdown", default=False)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Created", editable=False)
    updated = models.DateTimeField(auto_now=True, verbose_name="Edited", editable=False)
    deleted = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"{self.course.name} | {self.num} | {self.title}"

    def delete(self, *args):
        self.deleted = True
        self.save()

    class Meta:
        ordering = ("course", "num")
        verbose_name = _("Lesson")
        verbose_name_plural = _("Lessons")

mainapp/models/news.py
__all__ = ['News']

from django.db import models
from django.utils.translation import gettext_lazy as _


# Create your models here.
class News(models.Model):
    title = models.CharField(max_length=256, verbose_name="Title")
    preambule = models.CharField(max_length=1024, verbose_name="Preambule")
    body = models.TextField(blank=True, null=True, verbose_name="Body")
    body_as_markdown = models.BooleanField(default=False, verbose_name="As markdown")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Created", editable=False)
    updated = models.DateTimeField(auto_now=True, verbose_name="Edited", editable=False)
    deleted = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"{self.pk} {self.title}"

    def delete(self, *args):
        self.deleted = True
        self.save()


class Meta:
    verbose_name = _("News") # Название
    verbose_name_plural = _("News") # Название во множественном числе
    ordering = ("-created",) # Сортировка

mainapp/forms/feedback_form.py
from django import forms

from mainapp import models as mainapp_models
from mainapp.models import RatingChoices


class CourseFeedbackForm(forms.ModelForm):

    def __init__(self, *args, course=None, user=None, **kwargs):
        ret = super().__init__(*args, **kwargs)
        if course and user:
            self.fields["course"].initial = course.pk
            self.fields["user"].initial = user.pk
        return ret

    class Meta:
        model = mainapp_models.CourseFeedback
        fields = ("course", "user", "feedback", "rating")
        widgets = {
            "course": forms.HiddenInput(),
            "user": forms.HiddenInput(),
            "rating": forms.RadioSelect(choices=RatingChoices.choices),
        }

authapp/views/login_view.py
from django.contrib import messages
from django.contrib.auth.views import LoginView

from django.utils.safestring import mark_safe
from django.utils.translation import gettext_lazy as _


class CustomLoginView(LoginView):

    def form_valid(self, form):
        ret = super().form_valid(form)
        message = _("Login success!<br>Hi, %(username)s") % {
            "username": self.request.user.get_full_name()
            if self.request.user.get_full_name()
            else self.request.user.get_username()
        }
        messages.add_message(self.request, messages.INFO, mark_safe(message))
        return ret

    def form_invalid(self, form):
        for _unused, msg in form.error_messages.items():
            messages.add_message(
                self.request,
                messages.WARNING,
                mark_safe(f"Something goes wrong:<br>{msg}"),
            )
        return self.render_to_response(self.get_context_data(form=form))

library/mainapp/views.py
from rest_framework.viewsets import ModelViewSet
from .models import Author
from .serializers import AuthorModelSerializer


class AuthorModelViewSet(ModelViewSet):
    queryset = Author.objects.all()
    serializer_class = AuthorModelSerializer

mainapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import TemplateView


# Create your views here.

class ContactView(TemplateView):
    template_name = 'mainapp/contacts.html'


class CoursesListView(TemplateView):
    template_name = 'mainapp/courses_list.html'


class DocSiteView(TemplateView):
    template_name = 'mainapp/doc_site.html'


class IndexView(TemplateView):
    template_name = 'mainapp/index.html'


class LoginView(TemplateView):
    template_name = 'mainapp/login.html'


class NewsView(TemplateView):
    template_name = 'mainapp/news.html'

    def get_context_data(self, **kwargs):
        # Get all previous data
        context = super().get_context_data(**kwargs)
        # Create your own data
        context["news_title"] = "Громкий новостной заголовок"
        context["news_preview"] = "Предварительное описание, которое заинтересует каждого"
        context["range"] = range(5)
        return context


class NewsWithPaginatorView(NewsView):
    def get_context_data(self, page, **kwargs):
        context = super().get_context_data(page=page, **kwargs)
        context["page_num"] = page
        return context
























# class HelloWorldView(View):
#
#     def get(self, request, *args, **kwargs):
#         return HttpResponse('hello, world!')


# def hello_world(request):
#    return HttpResponse("hello")


# def blog(request):
#     return HttpResponse("i'm blog")

mainapp/templates/mainapp/contacts.html
{% extends 'base.html' %}
{% load email_to_link %}

{% block content %}

<p>
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Наши контакты</h1>
    <p class="lead">Обязательно свяжитесь с нами! Ваш комфорт - наша забота.</p>
  </div>
</div>
</p>
<p>
<div class="row justify-content-around mt-n2">

  <div class="col-sm-6 col-md-6 col-lg-4 pb-2">
    <div class="card h-100 shadow">
      <div class="card-body">
        <div style="position:relative;overflow:hidden;">
            <a href="https://yandex.ru/maps/org/petropavlovskaya_krepost/146720535721/?utm_medium=mapframe&utm_source=maps"
                style="color:#eee;font-size:12px;position:absolute;top:0px;">Петропавловская крепость</a>
            <a href="https://yandex.ru/maps/2/saint-petersburg/category/landmark_attraction/89683368508/?utm_medium=mapframe&utm_source=maps"
                style="color:#eee;font-size:12px;position:absolute;top:14px;">Достопримечательность в Санкт‑Петербурге</a>
            <a href="https://yandex.ru/maps/2/saint-petersburg/category/museum/184105894/?utm_medium=mapframe&utm_source=maps"
                style="color:#eee;font-size:12px;position:absolute;top:28px;">Музей в Санкт‑Петербурге</a>
            <iframe src="https://yandex.ru/map-widget/v1/-/CCUAZHcrhA" width="100%" height="300" frameborder="0"
                allowfullscreen="true" style="position:relative; border-radius: 4px;"></iframe>
        </div>
        <h5 class="card-title">Санкт‑Петербург</h5>
        <p class="card-text">
            <ul class="list-unstyled">
              <li>Телефон</li>
              <li><strong>+7-999-11-11111</strong></li>
            </ul>
            <ul class="list-unstyled">
              <li>Email</li>
              <li><strong>{{ 'geeklab@spb.ru'|email_to_link }}</strong></li>
            </ul>
            <ul class="list-unstyled">
              <li>Адрес</li>
              <li><strong>территория Петропавловская крепость, 3Ж</strong></li>
            </ul>
        </p>
      </div>
    </div>
  </div>

  <div class="col-sm-6 col-md-6 col-lg-4 pb-2">
    <div class="card h-100 shadow">
      <div class="card-body">
        <div style="position:relative;overflow:hidden;">
            <a href="https://yandex.ru/maps/org/kazanskiy_kreml/95813866834/?utm_medium=mapframe&utm_source=maps"
              style="color:#eee;font-size:12px;position:absolute;top:0px;">Казанский Кремль</a>
            <a href="https://yandex.ru/maps/43/kazan/category/museum/184105894/?utm_medium=mapframe&utm_source=maps"
              style="color:#eee;font-size:12px;position:absolute;top:14px;">Музей в Казани</a>
            <a href="https://yandex.ru/maps/43/kazan/category/landmark_attraction/89683368508/?utm_medium=mapframe&utm_source=maps"
              style="color:#eee;font-size:12px;position:absolute;top:28px;">Достопримечательность в Казани</a>
            <iframe src="https://yandex.ru/map-widget/v1/-/CCUAZHX3xB"  width="100%" height="300" frameborder="0"
              allowfullscreen="true" style="position:relative; border-radius: 4px;"></iframe>
        </div>
        <h5 class="card-title">Казань</h5>
        <p class="card-text">
        <ul class="list-unstyled">
          <li>Телефон</li>
          <li><strong>+7-999-22-22222</strong></li>
        </ul>
        <ul class="list-unstyled">
          <li>Email</li>
          <li><strong>{{ 'geeklab@kz.ru'|email_to_link }}</strong></li>
        </ul>
        <ul class="list-unstyled">
          <li>Адрес</li>
          <li><strong>территория Кремль, 11, Казань, Республика Татарстан, Россия</strong></li>
        </ul>
        </p>
      </div>
    </div>
  </div>

  <div class="col-sm-6 col-md-6 col-lg-4 pb-2">
    <div class="card h-100 shadow">
      <div class="card-body">
        <div style="position:relative;overflow:hidden;">
            <a href="https://yandex.ru/maps/org/sobor_pokrova_presvyatoy_bogoroditsy_na_rvu/175159255687/?utm_medium=mapframe&utm_source=maps"
              style="color:#eee;font-size:12px;position:absolute;top:0px;">Собор Покрова Пресвятой Богородицы на Рву</a>
            <a href="https://yandex.ru/maps/213/moscow/category/museum/184105894/?utm_medium=mapframe&utm_source=maps"
              style="color:#eee;font-size:12px;position:absolute;top:14px;">Музей в Москве</a>
            <iframe src="https://yandex.ru/map-widget/v1/-/CCUAZHh9kD" width="100%" height="300" frameborder="0"
              allowfullscreen="true" style="position:relative; border-radius: 4px;"></iframe>
        </div>
        <h5 class="card-title">Москва</h5>
        <p class="card-text">
        <ul class="list-unstyled">
          <li>Телефон</li>
          <li><strong>+7-999-33-33333</strong></li>
        </ul>
        <ul class="list-unstyled">
          <li>Email</li>
          <li><strong>{{ 'geeklab@msk.ru'|email_to_link }}<</strong></li>
        </ul>
        <ul class="list-unstyled">
          <li>Адрес</li>
          <li><strong>Красная площадь, 7, Москва, Россия</strong></li>
        </ul>
        </p>
      </div>
    </div>
  </div>

</div>
</p>

{% endblock content %}

  
</div>
</p>

mainapp/templates/mainapp/courses_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="row justify-content-center mt-3">
  <div class="card col-sm-12 col-md-6 col-lg-4 border-0">
    <a href="#">
      <img src="{% static '/img/course001.jpg' %}" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title text-center">Web Python</h5>
      </div>
    </a>
  </div>

  <div class="card col-sm-12 col-md-6 col-lg-4 border-0">
    <a href="#">
      <img src="{% static '/img/course002.jpg' %}" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title text-center">Web Golang</h5>
      </div>
    </a>
  </div>

  <div class="card col-sm-12 col-md-6 col-lg-4 border-0">
    <a href="#">
      <img src="{% static '/img/course003.jpg' %}" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title text-center">Web JavaScript</h5>
      </div>
    </a>
  </div>

  <div class="card col-sm-12 col-md-6 col-lg-4 border-0">
    <a href="#">
      <img src="{% static '/img/course004.jpg' %}" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title text-center">Web Java</h5>
      </div>
    </a>
  </div>

  <div class="card col-sm-12 col-md-6 col-lg-4 border-0">
    <a href="#">
      <img src="{% static '/img/course005.jpg' %}" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title text-center">Web PHP</h5>
      </div>
    </a>
  </div>

  <div class="card col-sm-12 col-md-6 col-lg-4 border-0">
    <a href="#">
      <img src="{% static '/img/course006.jpg' %}" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title text-center">Python AI</h5>
      </div>
    </a>
  </div>

  <div class="card col-sm-12 col-md-6 col-lg-4 border-0">
    <a href="#">
      <img src="{% static '/img/course007.jpg' %}" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title text-center">DevOps</h5>
      </div>
    </a>
  </div>

</div>
<div class="row justify-content-center align-items-center mt-3 mb-n3">
  <nav aria-label="Page navigation example">
    <ul class="pagination">
      <li class="page-item"><a class="page-link" href="#">Previous</a></li>
      <li class="page-item"><a class="page-link" href="#">1</a></li>
      <li class="page-item"><a class="page-link" href="#">2</a></li>
      <li class="page-item"><a class="page-link" href="#">3</a></li>
      <li class="page-item"><a class="page-link" href="#">Next</a></li>
    </ul>
  </nav>
</div>

{% endblock content %}

mainapp/templates/mainapp/doc_site.html
{% extends 'base.html' %}

{% block content %}

<div class="row justify-content-center align-items-center mt-3">
  <div class="col-md-9">
    <div class="card">
      <div class="card-header">
        Документация по сайту
      </div>
      <div class="card-body">
        <h5 class="card-title">CSS-стили</h5>
        <p class="card-text">
        <ul>
          <li><a href="https://getbootstrap.com/docs/4.6/getting-started/introduction/"
            target="_blank">Bootstrap v4.6</a>
          </li>
          <li><a href="https://bootswatch.com/lumen/" target="_blank">Bootstrap theme: Lumen</a></li>
        </ul>
        </p>

        <h5 class="card-title">Иконки</h5>
        <p class="card-text">
          <a href="https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use">FontAwesome 5.15.3</a>
        </p>

        <h5 class="card-title">Графики</h5>
        <p class="card-text"><a href="https://www.chartjs.org/">ChartJS</a></p>

        <h5 class="card-title">Графика</h5>
        <p class="card-text">
        <ul>
          <li><a href="https://www5.flamingtext.com/" target="_blank" rel="noopener noreferrer">Логотип by
              flamingtext.com</a>
          </li>
          <li><a href="https://www.pexels.com/ru-ru" target="_blank" rel="noopener noreferrer">Фотографии by
            pexels.com</a>. Все изображения распространяются под бесплатной лицензией. Для страницы обзоров фотографии
            должны быть с соотношением сторон кратным 2.912 (например, 1920x659)
          </li>
          <li><a href="https://getavataaars.com/" target="_blank" rel="noopener noreferrer">Аватарки пользователей by
              getavataaars.com</a>
          </li>
        </ul>
        </p>

      </div>
    </div>
  </div>
</div>

{% endblock content %}

mainapp/templates/mainapp/login.html
{% load static %}

<!doctype html>
<html lang="ru">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">

    <!-- ChartJS -->
    <link rel="stylesheet" href="{% static '/css/Chart.min.css' %}">

    <!-- FontAwesome -->
    <link rel="stylesheet" href="{% static '/css/fontawesome.all.min.css' %}">

    <title>Welcome to GeekLab!</title>
</head>

<body>





<div class="row justify-content-around align-items-center" style="height: 100vh; margin: 0px">
  <div class="text-center">
    <p>
      <a href="{% url 'mainapp:index' %}"><img src="{% static '/img/logo.png' %}" alt=""></a>
    </p>
    <h2>Вход пользователя</h2>
    <form>
      <p>
        <input id="id_username" class="form-control" type="text" name="username" placeholder="Имя пользователя"
          required="" autofocus="">
      </p>
      <p>
        <input id="id_password" class="form-control" type="password" name="password" placeholder="Пароль" required="">
      </p>
      <p>
        <button type="submit" class="btn btn-primary btn-block">Войти</button>
      </p>
    </form>
    <p class="text-right">
      <a href=""><small>Забыли пароль?</small></a>
    </p>
    <h4>Вход через социальные сети</h4>
    <p>
    <div class="btn-group btn-block" role="group">
      <a class="btn btn-primary" href="#" role="button"><i class="fab fa-vk"></i></a>
      <a class="btn btn-primary" href="#" role="button"><i class="fab fa-github"></i></a>
      <a class="btn btn-primary" href="#" role="button"><i class="fab fa-facebook"></i></a>
    </div>
    </p>
  </div>
</div>








    <!-- JavaScript section -->
    <!-- Bootstrap -->
    <script src="{% static '/js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static '/js/popper.min.js' %}"></script>
    <script src="{% static '/js/bootstrap.min.js' %}"></script>

    <!-- ChartJs -->
    <script src="{% static '/js/Chart.min.js' %}"></script>

    <!-- FontAwesome -->
    <script src="{% static '/js/fontawesome.all.min.js' %}"></script>



</body>

</html>

mainapp/templates/mainapp/news.html
{% extends 'base.html' %}

{% block content %}

{% with range as double_range %}

{% if page_num %}
 <div class="card my-2">
   <div class="card-body">
     <p class="card-text">Текущая страница: {{ page_num }}</p>
   </div>
 </div>
{% endif %}

<div class="row">

  <div class="col-lg-8">

    {% for i in double_range %}
    <div class="card my-2">
      <div class="card-body">
        <h5 class="card-title">{{ news_title }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">
          {{ datetime_obj|date:"Y-m-d h-i-s" }}
            {% comment %} https://django.fun/ru/docs/django/3.2/ref/templates/builtins/
            {% endcomment %}
        </h6>
        <p class="card-text">{{ news_preview }}</p>
        <a href="#" class="card-link">Подробнее</a>
      </div>
    </div>
    {% endfor %}



  </div>

  <div class="col-lg-4">
    <div class="card my-2 sticky-top">
      <div class="card-header">
        Фильтры
      </div>
      <div class="card-body">
        <form action="">
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon1">Дата от...</span>
            </div>
 <input type="date" class="form-control" name="dateFrom">
          </div>
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon1">Дата до...</span>
            </div>
            <input type="date" class="form-control" name="dateTo">
          </div>
          <button type="submit"
            class="btn btn-primary btn-block">Фильтровать</button>
        </form>
      </div>
    </div>
  </div>

</div>

<div class="row justify-content-center align-items-center mt-3 mb-n3">
  <nav aria-label="Page navigation example">
    <ul class="pagination">
      <li class="page-item"><a class="page-link" href="#">Previous</a></li>
      <li class="page-item"><a class="page-link" href="{% url 'mainapp:news_paginator' 1 %}">1</a></li>
      <li class="page-item"><a class="page-link" href="{% url 'mainapp:news_paginator' page=2 %}">2</a></li>
      <li class="page-item"><a class="page-link" href="{% url 'mainapp:news_paginator' page=3 %}">3</a></li>
<!--       {# <li class="page-item"><a class="page-link" href="{% url 'mainapp:news_paginator' three %}">3</a></li> #}-->
      <li class="page-item"><a class="page-link" href="#">Next</a></li>
    </ul>
  </nav>
</div>

{% endwith %}

{% endblock content %}